[versions]
java = "25"
kotlin = "2.3.0"

spring-boot = "4.0.1"
spring-dependency-management = "1.1.7"
spring-cloud = "2025.1.0"

jjwt = "0.13.0"
springdoc = "3.0.0"
postgres = "42.7.8"
hibernate = "7.2.0.Final"
geoip = "5.0.2"
mockito-kotlin = "6.1.0"

ktlint = "14.0.1"


[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }

spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }

ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }


[libraries]
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

spring-boot-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }
spring-boot-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-boot-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-liquibase = { module = "org.springframework.boot:spring-boot-starter-liquibase" }
spring-boot-test = { module = "org.springframework.boot:spring-boot-starter-test" }

spring-cloud-eureka-client = { module = "org.springframework.cloud:spring-cloud-starter-netflix-eureka-client" }
spring-cloud-eureka-server = { module = "org.springframework.cloud:spring-cloud-starter-netflix-eureka-server" }
spring-cloud-gateway = { module = "org.springframework.cloud:spring-cloud-starter-gateway-server-webflux" }
spring-cloud-bom = { module = "org.springframework.cloud:spring-cloud-dependencies", version.ref = "spring-cloud" }

springdoc-webmvc = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }
springdoc-webflux = { module = "org.springdoc:springdoc-openapi-starter-webflux-ui", version.ref = "springdoc" }

postgresql = { module = "org.postgresql:postgresql", version.ref = "postgres" }
hibernate-core = { module = "org.hibernate:hibernate-core", version.ref = "hibernate" }

jjwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jjwt" }
jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwt" }
jjwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jjwt" }

geoip = { module = "com.maxmind.geoip2:geoip2", version.ref = "geoip" }

mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }
