server:
  port: 9000

spring:
  application:
    name: authentication-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:AuthenticationServiceDB}
    username: ${POSTGRES_USER:auth-service-user}
    password: ${POSTGRES_PASSWORD:odn1Dl}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    show-sql: off
    database: postgresql

  liquibase:
    change-log: classpath:/db/changelog.xml
    enabled: true

springdoc:
  swagger-ui:
    enabled: true
    path: /authentication-service/swagger-ui
  api-docs:
    enabled: true
    path: /authentication-service/v3/api-docs

eureka:
  instance:
    hostname: authentication-service
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: WARN
    web: WARN

security:
  jwt:
    secret: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expires-in: 12960000
